name: Build Assets

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'resources/**.js'
      - 'resources/**.scss'
      - 'resources/**.php'
  pull_request:
    branches: [ master ]
    paths:
      - 'resources/**.js'
      - 'resources/**.scss'
      - 'resources/**.php'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: cd $GITHUB_WORKSPACE

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install dependencies
      run: npm install

    - name: Run build script
      run: npm run prod

    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.2.1
      with:
        add: 'public'
        message: 'Build production assets via GitHub Actions'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
